server:
  port: 9000

spring:
  http.converters.preferred-json-mapper: jackson
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost/clientapp?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        hbm2ddl:
          auto: validate
  flyway:
    locations: classpath:db/migration
